version: 2
jobs:
  build:
    machine: true
    working_directory: '~/dcos-net'
    environment:
      - OTP_VERSION: "21.3"
    steps:
      - checkout
      - restore_cache:
          key: otp-build-21.3
      - run:
          name: Building OTP
          command: |
              if [ -d ~/src/otp ]; then
                  echo "Use pre-build OTP version"
                  exit 0
              fi

              set -xe
              ( mkdir -p ~/src && cd ~/src \
                && git clone --branch maint-21 https://github.com/erlang/otp.git )
              ( cd ~/src/otp \
                && git checkout 620ac3e68c5bc8b36143965fcf2892a07dc005c4 \
                && ./otp_build autoconf \
                && ./configure \
                && make -j$(getconf _NPROCESSORS_ONLN) )
      - save_cache:
          key: otp-build-21.3
          paths:
            - ~/src/otp
      - run:
          name: Installing OTP
          command: (cd ~/src/otp && sudo make install)
      - run:
          name: Installing libsodium
          command: |
              set -xe
              curl -LO https://launchpad.net/ubuntu/+archive/primary/+files/libsodium18_1.0.13-1_amd64.deb
              curl -LO https://launchpad.net/ubuntu/+archive/primary/+files/libsodium-dev_1.0.13-1_amd64.deb
              sudo dpkg -i libsodium18_1.0.13-1_amd64.deb
              sudo dpkg -i libsodium-dev_1.0.13-1_amd64.deb
      - run:
          name: Updating rebar3
          command: ./rebar3 update
      - run:
          name: Fetching dependencies
          command: ./rebar3 get-deps
      - run:
          name: Building
          command: ./rebar3 compile
      - run:
          name: Building OTP release
          command: ./rebar3 as prod release
      - run:
          name: Installing test dependencies
          command: |
              set -xe
              sudo apt-get update
              sudo apt-get install -y --no-install-recommends \
                  iproute2 dnsutils ipvsadm
      - run:
          name: Starting EPMD
          command: epmd -daemon
      - run:
          name: Checking eunit tests
          command: ./rebar3 eunit --verbose
      - run:
          name: Collecting eunit cover reports
          command: |
              set -xe
              ./rebar3 as test cover
              ./rebar3 as test covertool generate
              ./rebar3 as test cover --reset
              mkdir _build/test/covertool/eunit
              mv _build/test/covertool/*.covertool.xml _build/test/covertool/eunit/
      - run:
          name: Checking common tests
          command: ./rebar3 ct --verbose --readable true
      - run:
          name: Collecting ct cover reports
          command: |
              set -xe
              ./rebar3 as test cover
              ./rebar3 as test covertool generate
              ./rebar3 as test cover --reset
              mkdir _build/test/covertool/ct
              mv _build/test/covertool/*.covertool.xml _build/test/covertool/ct/
      - run:
          name: Checking common tests as root
          command: sudo $(which escript) ./rebar3 ct --verbose --readable true
      - run:
          name: Collecting ct2 cover reports
          command: |
              set -xe
              ./rebar3 as test cover
              ./rebar3 as test covertool generate
              ./rebar3 as test cover --reset
              mkdir _build/test/covertool/ct2
              mv _build/test/covertool/*.covertool.xml _build/test/covertool/ct2/
      - run:
          name: Running cross reference analysis
          command: ./rebar3 xref
      - run:
          name: Running static analyzer
          command: ./rebar3 dialyzer
      - run:
          name: Checking code style
          command: ./rebar3 as lint lint
      - run:
          name: Installing codecov
          command: pip install codecov
      - run:
          name: Sending cover reports
          command: |
              set -xe
              codecov -X gcov -F eunit -f _build/test/covertool/eunit/*.covertool.xml
              codecov -X gcov -F ct -f _build/test/covertool/ct/*.covertool.xml
              codecov -X gcov -F ct2 -f _build/test/covertool/ct2/*.covertool.xml
      - store_artifacts:
          path: ~/dcos-net/_build/test/logs
